export const MY_CHATS_ROUTE: string = "/my"
export const CONTACTS_ROUTE: string = "/contacts"
export const CREATE_CHAT_ROUTE: string = "/create_chat"
export const PROFILE_ROUTE: string = "/profile"
export const ALL_USERS_ROUTE: string = "/users"
export const CHATS_ROUTE: string = "/chats"
export const REGISTRATION_ROUTE: string = "/reg"
export const LOGIN_ROUTE: string = "/log"